### ISSUE TITLE
stackql-exec action pass variable to iql file

### ISSUE THREAD

**Issue by yunchengyang515** [stackql/stackql-exec#12]
https://stackoverflow.com/questions/2914220/bash-templating-how-to-build-configuration-files-from-templates-with-bash/11050943#11050943

**Comment by jeffreyaven** [comment]
closed with https://github.com/stackql/stackql-exec/pull/14, supports ext vars using inline `jsonnet` see : https://github.com/stackql/stackql-exec/blob/main/.github/workflows/stackql-exec.yml#L58 and https://github.com/stackql/stackql-exec/blob/main/stackql_scripts/google-instances-by-status-with-vars.iql
